### ISSUE TITLE
How to hide the daily push by the Github Actions？

### ISSUE THREAD

**Issue by dukechain2333** [yoshi389111/github-profile-3d-contrib#23]
Hi there! 

Your repo is gorgeous. Thanks for sharing.
But I have some questions about it.
You see, your Github Actions push a new generated svg everyday, but I can't see the push in your contribution box as well as your newly generated svg, just like below.
<img width="792" alt="image" src="https://user-images.githubusercontent.com/57356723/143777668-07d1c451-0c50-4d5e-90e0-cd12710e3a9f.png">
 
I can only suppose you did something special that can filter the automatic push. 
Could you share your method of how you doing that?  I will be really appreciate it.

**Comment by yoshi389111** [comment]
Hi dukechain2333. Thanks for visiting my repository.

See the following github help.

[Why are my contributions not showing up on my profile?](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile)

>Commits will appear on your contributions graph if they meet all of the following conditions:
>
> * The email address used for the commits is associated with your account on GitHub.com.
> * ...

If you commit with an email address that is not associated with github, you will not be recognized as a contributor.

**Comment by dukechain2333** [comment]
Roger that. Thanks a lot
