### ISSUE TITLE
Profile green animate dark svg

### ISSUE THREAD

**Issue by somekindofwallflower** [yoshi389111/github-profile-3d-contrib#24]
I would prefer to have also another svg that has 

- color green
- animation
- dark mode

**Comment by formidablae** [comment]
Implemented in PR #25

**Comment by yoshi389111** [comment]
Ciao @somekindofwallflower 
Thanks for the suggestion.

Indeed, I also think it would be better to have a green version of dark mode.

I'll add it in ver 0.4.0.
