### ISSUE TITLE
Workflow run is failing

### ISSUE THREAD

**Issue by chinmay29hub** [yoshi389111/github-profile-3d-contrib#26]
Description : Workflow runs when I run it manually but fails in automatic run.

**Comment by yoshi389111** [comment]
Hi chinmay29hub. Thanks for visiting my repository.

Does automatic run always fail?

In my case, I ran it once a day for about 8 months, and it failed only once.
At that time, I think the load on the GitHub server was probably too high.

**Comment by chinmay29hub** [comment]
![issue](https://user-images.githubusercontent.com/69494946/150544027-4bd62bf0-d307-476e-8062-7c2bcc20c25c.png)
<br>
so, please refer the ouput in the image of the failing task. Also I am running two more different workflows for different tasks. Does this cause the problem or the time i have to given in the yaml file (it is - cron: "0 */2 * * *"  ? If it is what is the least difference time I can specify that will not cause the issue.

**Comment by yoshi389111** [comment]
Looking at that image, it seems that there is no file output.

You have created a personal access token named `PROFILE_TOKEN`.
It is possible that you do not have enough permissions on that token.
Please give `repo:status` and `read:user` permissions.

Or, if you don't need private repository contributions, try using `secrets.GITHUB_TOKEN`.

**Comment by chinmay29hub** [comment]
I have given all permissions to that token

**Comment by yoshi389111** [comment]
You run it once every two hours.

If the number of contributions does not change during the two hours, the file to be output will not change.
So I think you are getting an error that there is no diff and nothing to commit.

Either make it once every 24 hours, or add `--allow-empty` when you commit.

```diff
-    - cron: "0 */2 * * *"
+    - cron: "30 21 * * *"
```

or

```diff
-          git commit -m "generated"
+          git commit -m "generated" --allow-empty
```
