### ISSUE TITLE
Height of bars in days with more than 50 contributions is always 153

### ISSUE THREAD

**Issue by formidablae** [yoshi389111/github-profile-3d-contrib#27]
**Describe the bug**
Height of days with more than 50 contributions is always 153.
`const calHeight = Math.min(50, cal.contributionCount) * 3 + 3;`
https://github.com/formidablae/github-profile-3d-contrib/blob/210fbaf3147b61d63405df0a043af830a252bfe5/src/create-3d-contrib.ts#L219

**To Reproduce**
1. Do 51 contributions in a day.
2. Do 65 contributions in the next day.
3. Generate the 3D contributions svg image.
4. Both days will have same height.

**Expected behavior**
Days with different contributions should have different heights.
Days with more contributions should have taller bars than days with fewer contributions.
Days with same number of contributions (in the last 365 days) should have same height of the bar.

**Screenshots**
Is now:
![image](https://user-images.githubusercontent.com/81068781/150635266-f5be3091-e4e3-43ed-8803-0555f72346f3.png)
even though those days have different contribution numbers.
![image](https://user-images.githubusercontent.com/81068781/150635289-099dc583-af29-487e-9f1d-dcda6d062319.png)

**A possibile solution**
Since some users might have days with hundreds of contributions and other days with very few - therefore the bar height difference would be huge and not nice to show linearly, I propose the usage of logarithmic height for the bars. ( in the form of `height = log(num_contribs * constant_a + constant_b)`.
`constant_b` helps keep decent the height of days with a small number of contributions. When a users starts having more and more contribs, `constant_b` starts having less influence on the height.
Example  (number of contributions -> corresponding height):
1 contribution -> log(1 contrib * 5 + 10) = log(15) = 1.18
2 contribs -> log(2 * 5 + 10) = 1.3
5 contribs -> log(35) = 1.54
10 contribs -> log(60) = 1.78 (going from 1 contribs to 10, increases height by 0.6, +50%)
20 contribs -> log(110) = 2.04
50 contribs -> log(260) = 2.41
100 contribs -> log(510) = 2.71 (going from 10 contribs to 100, increases height by 0.93, +52%)
200 contribs -> log(1010) = 3.00
500 contribs -> log(2510) = 3.40
1000 contribs -> log(5010) = 3.70 (going from 100 contribs to 1000, increases height by 0.99, +37%)
10000 contribs -> log(50010) = 4.70 (going from 100 contribs to 1000, increases height by 1, +27%)
For each order of 10 increase, there would be approximately an increase in height of 1 with relative percentage increase continually decreasing. 
This way infinity isn't avoided but height difference between days is preserved and visually it might be nice(r) (play with the constants for a better result - maybe add some other constant related to the average of contributions in the last 365 days).

**Comment by formidablae** [comment]
You are welcome @yoshi389111 :)
Your adjusted solution is better. I didn't know about the max 1200 contributions per day.
Nicely done that reverse parameter calculation!

> However, 1200 contributions per day may be too much.

Yeah, you are right. But, since the heights of **all** days will be recalculated, there shouldn't be unusual differences between them (even with way less contributions than 1200).

Did you do produce any 3d svg with the new formula? Are the heights too low or too high when compared to the heights obtained with the old formula?

**Comment by yoshi389111** [comment]
> I didn't know about the max 1200 contributions per day.

I may have misled you.

1200 is not the maximum number of contributions per day on github.
It is the maximum number of contributions that can be displayed in this tool without overlapping or overflowing.

> Are the heights too low or too high when compared to the heights obtained with the old formula?

With this formula, the display seems to be too small.

I would like to adjust the formula so that it can be displayed a little larger.

**Comment by formidablae** [comment]
> 1200 ... is the maximum number of contributions that can be displayed in this tool without overlapping or overflowing.

Oh ok, now I get it.

> With this formula, the display seems to be too small.
> I would like to adjust the formula so that it can be displayed a little larger.

Did you try doing an average of the old linear formula and the new logarithmic one?

![image](https://user-images.githubusercontent.com/81068781/151079382-b3869f48-0ac4-4c8a-b78a-156d8d65004a.png)

**Comment by yoshi389111** [comment]
I tried the following formula.

`(log10(x*12/5+1)*72 + min(x,50)*3) / 2 + 3`

It is uncomfortable to have a small number of contributes.

![fig1](https://user-images.githubusercontent.com/15214393/151269515-6582077d-4a1d-443a-a03d-6e22c31f7c1b.png)

![fig2](https://user-images.githubusercontent.com/15214393/151267173-9d7021ad-0dfa-4f35-b1cf-9f2bb198a858.png)

![fig3](https://user-images.githubusercontent.com/15214393/151270572-434ef0ab-09ef-4f19-9703-c66effcb2a4a.png)


I thought of using the following formula.

`log10(x/20+1)*144+3`

It is a little smaller, but I think it is acceptable.

![fig4](https://user-images.githubusercontent.com/15214393/151267689-1cbe7d95-26c0-4b40-9dcd-d2a217bc866b.png)

![fig5](https://user-images.githubusercontent.com/15214393/151268005-13ca7338-24eb-45af-a069-afd1cbd15bcc.png)

![fig6](https://user-images.githubusercontent.com/15214393/151269064-5243665a-0c33-4c0f-880e-20a4c230dc3d.png)

**Comment by formidablae** [comment]
Wow, the second one looks wonderful! Even though the absolute height of 51 contributions/day would now be lower than before, the differences between the heights of different days would still be very distinguishable, colors help too - so that last formula works perfect (for me at least :) ).
