### ISSUE TITLE
Availability to configure lang?

### ISSUE THREAD

**Issue by ppizarror** [yoshi389111/github-profile-3d-contrib#30]
**Is your feature request related to a problem? Please describe.**
Hi! First of all thanks for this epic software. It really adds tons of info even for displaying on personal websites!

For the very same reason, I think it can be very useful if the language of the generated svg could be changed, and the path of the files too.

**Describe the solution you'd like**
To enable i18n, the following key can be added to json (Spanish):

```json
{
  "type": "normal",
  ...
  "i18n": {
      "commit": "Commit",
      "repo": "Repositorios",
      "review": "Revisiones",
      "pullreq": "Pull/Req",
      "issue": "Issues",
      "contributions": "contribuciones",
  },
  "exportpath": "profile-3d-contrib-es"
}
```

Thus, I'd have two different paths, 1 for english (default), and another for Spanish entries, and so on...
Thanks!

**Comment by yoshi389111** [comment]
Hi ppizarror. Thank you for your proposal.

I made the following changes In version 0.7.0.

* #35 
* #36 
* #37

```diff
  {
    "type": "normal",
+   "fileName": "profile-custom-spanish.svg",
    "backgroundColor": "#ffffff",
    "foregroundColor": "#00000f",
    "strongColor": "#111133",
    "weakColor": "gray",
    "radarColor": "#47a042",
    "growingAnimation": true,
    "contribColors": [
      "#efefef",
      "#d8e887",
      "#8cc569",
      "#47a042",
      "#1d6a23"
    ],
+   "l10n": {
+     "commit": "Commit",
+     "repo": "Repositorios",
+     "review": "Revisiones",
+     "pullreq": "Pull/Req",
+     "issue": "Issues",
+     "contrib": "contribuciones"
+   }
  }
```
