### ISSUE TITLE
401

### ISSUE THREAD

**Issue by xandner** [yoshi389111/github-profile-3d-contrib#52]
hi. im trying to use github-profile-3d-contrib. 
im created a github action and this is my profile-3d.yml :
`
name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN:  my-token
          USERNAME: xandner
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
`
but when i run the action get a :
Request failed with status code 401

**Comment by yoshi389111** [comment]
Hello xandner.

I think your github token is wrong.
Please refer to the following page.

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

Also, do not write the github token directly in your workflow yaml. Others may abuse it. I recommend deleting the current token and recreating it.

Register the created access token as secret information for the repository by referring to the following page.

https://docs.github.com/en/actions/security-guides/encrypted-secrets

If you have registered with the name "MY_TOKEN", register it in the workflow as follows.

```
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
```

Also, if you don't want to include private repository activities, you don't need to create a token and the example definition works.

```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by Drjacky** [comment]
@yoshi389111 
I created the `MY_TOKEN` but I get:
> GITHUB_TOKEN is empty
