### ISSUE TITLE
Node.js 12 actions are deprecated. How to upgrade?

### ISSUE THREAD

**Issue by hhrwvyy5654v** [yoshi389111/github-profile-3d-contrib#54]
**Describe the bug**
When I deployed according to the readme of https://github.com/yoshi389111/github-profile-3d-contrib, the following error message occurred:

Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: yoshi389111/github-profile-3d-contrib@0.7.0. For more information see: https://github.blog/changelog/2022 -09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

I would like to know how to solve this problem, properly deploy and run the project "generate-github-profile-3d-contrib".

**Screenshots**
![image](https://user-images.githubusercontent.com/75118328/234306440-74c93dca-b4f3-411e-9aa2-1be4e6cabe94.png)
![image](https://user-images.githubusercontent.com/75118328/234307785-1741d240-d131-4c43-9358-208be5aac9d4.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Professional Edition]
 - Browser [Chrome]
 - Version [111.0.5563.147 (official release) (64-bit)]

**Comment by yoshi389111** [comment]
Hello, hhrwvyy5654v.

Version 0.7.1 now uses node16.

Please use version 0.7.1.

```diff
  name: 3D-Contrib

  on:
    schedule:
      - cron: "0 0 * * *"
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
      name: generate-github-profile-3d-contrib
      steps:
        - uses: actions/checkout@v3
-       - uses: yoshi389111/github-profile-3d-contrib@0.7.0
+       - uses: yoshi389111/github-profile-3d-contrib@0.7.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            USERNAME: ${{ github.repository_owner }}
        - name: Commit & Push
          run: |
            git config user.name hhrwvyy5654v
            git config user.email huang_rongquan@outlook.com
            git add -A .
            git commit -m "generated"
            git push
```
