### ISSUE TITLE
Count private repo changes

### ISSUE THREAD

**Issue by XGavinp** [yoshi389111/github-profile-3d-contrib#73]
Hi I am getting this error can u help me solve it.

Run git config user.name github-actions
[main 65d4775] generated
 [10](https://github.com/XGavinp/XGavinp/actions/runs/7152624235/job/19478144203#step:4:11) files changed, 10 insertions(+)
 create mode 100644 profile-3d-contrib/profile-gitblock.svg
 create mode 100644 profile-3d-contrib/profile-green-animate.svg
 create mode 100644 profile-3d-contrib/profile-green.svg
 create mode 100644 profile-3d-contrib/profile-night-green.svg
 create mode 100644 profile-3d-contrib/profile-night-rainbow.svg
 create mode 100644 profile-3d-contrib/profile-night-view.svg
 create mode 100644 profile-3d-contrib/profile-season-animate.svg
 create mode 100644 profile-3d-contrib/profile-season.svg
 create mode 100644 profile-3d-contrib/profile-south-season-animate.svg
 create mode 100644 profile-3d-contrib/profile-south-season.svg
remote: Permission to XGavinp/XGavinp.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/XGavinp/XGavinp/': The requested URL returned error: 403
Error: Process completed with exit code [12](https://github.com/XGavinp/XGavinp/actions/runs/7152624235/job/19478144203#step:4:13)8.

**Comment by XGavinp** [comment]
Can u pls help me solve this error

**Comment by E-sion** [comment]
#51 
This will help you.

**Comment by XGavinp** [comment]
Hi,

Thank u so much. It worked.

**Comment by XGavinp** [comment]
Hi want it to count my private repo changes also. How do i do that?

**Comment by ethanuppal** [comment]
How was this completed? did you successfully count your private contributions?

**Comment by XGavinp** [comment]
Yes
