### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Thecode764** [yoshi389111/github-profile-3d-contrib#80]
Hmmmm i run the action
error
Run git config user.name github-actions
[main 3bff596] generated
 10 files changed, 10 insertions(+)
 create mode 100644 profile-3d-contrib/profile-gitblock.svg
 create mode 100644 profile-3d-contrib/profile-green-animate.svg
 create mode 100644 profile-3d-contrib/profile-green.svg
 create mode 100644 profile-3d-contrib/profile-night-green.svg
 create mode 100644 profile-3d-contrib/profile-night-rainbow.svg
 create mode 100644 profile-3d-contrib/profile-night-view.svg
 create mode 100644 profile-3d-contrib/profile-season-animate.svg
 create mode 100644 profile-3d-contrib/profile-season.svg
 create mode 100644 profile-3d-contrib/profile-south-season-animate.svg
 create mode 100644 profile-3d-contrib/profile-south-season.svg
remote: Permission to Thecode764/Thecode764.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/Thecode764/Thecode764/': The requested URL returned error: 403
Error: Process completed with exit code 128.

**Comment by KenSolem** [comment]
yo tengo el mismo error y es por el .node version. no he encontrado solución aun.
