### ISSUE TITLE
remote: Permission to...

### ISSUE THREAD

**Issue by mobinjavari** [yoshi389111/github-profile-3d-contrib#81]
![image](https://github.com/user-attachments/assets/e00952fc-65b8-4f54-9321-74c7c8d36483)

**Describe the bug**
[remote: Permission to mobinjavari/mobinjavari.git denied to github-actions[bot].
](https://github.com/mobinjavari/mobinjavari/actions/runs/10253869123/job/28367462789)
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NarciSource** [comment]
This link provides a solution. https://github.com/yoshi389111/github-profile-3d-contrib/issues/51#issuecomment-1432257902
